### ISSUE TITLE
Kubernetes deployment not accessible

### ISSUE THREAD

**Issue by salonijuneja27** [anchore/anchore_deployment#2]
On following the README in scalable folder. The deployment that is created is not accessible. None of the ports are listening and the logs are not getting populated. Cannot seem to find the problem.
Please let me know if you get any information.

**Comment by nurmi** [comment]
Hi @salonijuneja27 - we’ll do a review, and in order to best do so, it would be helpful if you could share information about your environment (kubernetes deployment mechanism, version, etc), any anchore configurations files that you can share, and any logging and command output to show us your process thus far (starting up, determining that logs are not being populated, etc).

Best Regards,
Dan

**Comment by salonijuneja27** [comment]
Hi Dan,
Thanks for the response.

**Comment by zhill** [comment]
@salonijuneja27 , there are two deployments created, one is the [core services deployment](https://github.com/anchore/anchore_deployment/blob/master/kubernetes/scalable/anchore-engine-core-deployment.yaml) which is exposed via the core service definition [core service definition](https://github.com/anchore/anchore_deployment/blob/master/kubernetes/scalable/anchore-engine-core-service.yaml). The other is the [analyzer deployment](https://github.com/anchore/anchore_deployment/blob/master/kubernetes/scalable/anchore-engine-analyzer-deployment.yaml), which does not get an endpoint/service definition because those pods only pull tasks from apis exposed by the core.

To use the system, you configure your client to access the core service dns name and port.

**Comment by zhill** [comment]
Closing due to no response/activity in a long time.
